/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skola;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Severin
 */
public class Dodavanje_ucenika extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    PreparedStatement pst1;
    ResultSet rs;
    /**
     * Creates new form dodavanje_ucenika
     */
    public Dodavanje_ucenika() {
        initComponents();
        tablica_ucenik();
        maticna_knjiga();
    }
//  TABLICA 
 public void tablica_ucenik()
    {
        int c;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ematicna_baza","root",""); 
            pst = con.prepareStatement("select * from ucenik");
            ResultSet Rs = pst.executeQuery();
            
            ResultSetMetaData rd = Rs.getMetaData();
            c = rd.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)jTable_tablica.getModel();
            df.setRowCount(0);
            
            while(Rs.next())
            {
               Vector v2 = new Vector();
               
               for(int i=1; i<c; i++)
               {
                  v2.add(Rs.getString("id"));
                   v2.add(Rs.getString("iducenik"));
                   v2.add(Rs.getString("maticna_knjiga"));
                   v2.add(Rs.getString("maticni_broj"));
                   v2.add(Rs.getString("ime"));
                   v2.add(Rs.getString("prezime"));
                   v2.add(Rs.getString("jmbg"));
                   v2.add(Rs.getString("spol"));
                   v2.add(Rs.getString("roditelj"));
                   v2.add(Rs.getString("datum_rodjenja"));    
                   v2.add(Rs.getString("mjesto_rodjenja"));
                   v2.add(Rs.getString("opcina_rodjenja"));
                   v2.add(Rs.getString("drzava_rodjenja"));
                   v2.add(Rs.getString("drzavljanstvo"));
                   v2.add(Rs.getString("nacionalnost"));
                   v2.add(Rs.getString("godina_prvog_razreda"));
               }
               df.addRow(v2);
            }  
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dodavanje_ucenika.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
           Logger.getLogger(Dodavanje_ucenika.class.getName()).log(Level.SEVERE, null, ex);
       }
            
    }    
 
 
//  Maticna knjiga 
public void maticna_knjiga()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ematicna_baza","root","");    
            pst1 = con.prepareStatement("select * from maticna_knjiga");
            rs = pst1.executeQuery();
            
            txtMaticna_knjiga.removeAllItems();
            
            while(rs.next())
            {
                txtMaticna_knjiga.addItem(rs.getString(2));
            }
              
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dodavanje_ucenika.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Dodavanje_ucenika.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame_formular = new javax.swing.JInternalFrame();
        jLabel_ime = new javax.swing.JLabel();
        jLabel_prezime = new javax.swing.JLabel();
        jLabel_spol = new javax.swing.JLabel();
        jLabel_imena_roditelja = new javax.swing.JLabel();
        jLabel_datum_rodjenja = new javax.swing.JLabel();
        jLabel_mjesto_rodjenja = new javax.swing.JLabel();
        jLabel_opcina_rodjenja = new javax.swing.JLabel();
        jLabel_drzava_rodjenja = new javax.swing.JLabel();
        jLabel_drzavljanin = new javax.swing.JLabel();
        jLabel_narodnost = new javax.swing.JLabel();
        jButton_Spremi_ = new javax.swing.JButton();
        jButton_Odustani_ = new javax.swing.JButton();
        jLabel_maticna_knjiga = new javax.swing.JLabel();
        jLabel_maticni_broj = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jRadioButton_Spol = new javax.swing.JRadioButton();
        jRadioButton_Spol_ = new javax.swing.JRadioButton();
        txtPrezime = new javax.swing.JTextField();
        txtIme_roditelja = new javax.swing.JTextField();
        txtDatum_rodjenja = new javax.swing.JTextField();
        txtMjesto_rodjenja = new javax.swing.JTextField();
        txtOpcina_rodjenja = new javax.swing.JTextField();
        txtDrzava_rodjenja = new javax.swing.JComboBox();
        txtDrzavljanin = new javax.swing.JTextField();
        txtNarodnost = new javax.swing.JComboBox();
        txtMaticna_knjiga = new javax.swing.JComboBox();
        txtMaticni_broj = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtidUcenika = new javax.swing.JTextField();
        jLabel_iducenik = new javax.swing.JLabel();
        txtJmbg = new javax.swing.JTextField();
        jLabel_jmbg = new javax.swing.JLabel();
        txtGodina_prvog_razreda = new javax.swing.JTextField();
        jLabel_godina_prvog_razreda = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_tablica = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame_formular.setBackground(new java.awt.Color(204, 204, 204));
        jInternalFrame_formular.setIconifiable(true);
        jInternalFrame_formular.setTitle("Matični podaci učenika");
        jInternalFrame_formular.setToolTipText(" ");
        jInternalFrame_formular.setVisible(true);

        jLabel_ime.setText("Ime");

        jLabel_prezime.setText("Prezime");

        jLabel_spol.setText("Spol");

        jLabel_imena_roditelja.setText("Imena roditelja");

        jLabel_datum_rodjenja.setText("Datum rođenja");

        jLabel_mjesto_rodjenja.setText("Mjesto rođenja");

        jLabel_opcina_rodjenja.setText("Općina rođenja");

        jLabel_drzava_rodjenja.setText("Država rođenja");

        jLabel_drzavljanin.setText("Državljanin");

        jLabel_narodnost.setText("Narodnost");

        jButton_Spremi_.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Spremi_.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton_Spremi_.setText("Spremi");
        jButton_Spremi_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Spremi_ActionPerformed(evt);
            }
        });

        jButton_Odustani_.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Odustani_.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton_Odustani_.setText("Odustani");
        jButton_Odustani_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Odustani_ActionPerformed(evt);
            }
        });

        jLabel_maticna_knjiga.setText("Matična knjiga");

        jLabel_maticni_broj.setText("Matični broj ");

        jRadioButton_Spol.setText("Muško");

        jRadioButton_Spol_.setText("Žensko");

        txtIme_roditelja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIme_roditeljaActionPerformed(evt);
            }
        });

        txtDatum_rodjenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatum_rodjenjaActionPerformed(evt);
            }
        });

        txtDrzava_rodjenja.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bosna i Hercegovina\t", "Republika Hrvatska ", "Srbija ", "Austrija", "Njemačka ", "Švicarska ", "Italija", "Ostalo", " ", " " }));

        txtNarodnost.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hrvat ", "Bošnjak", "Srbin", "Ostalo", " " }));

        txtMaticna_knjiga.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtMaticna_knjigaItemStateChanged(evt);
            }
        });

        txtMaticni_broj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaticni_brojActionPerformed(evt);
            }
        });
        txtMaticni_broj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaticni_brojKeyReleased(evt);
            }
        });

        txtidUcenika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidUcenikaActionPerformed(evt);
            }
        });

        jLabel_iducenik.setText("ID Učenika");

        jLabel_jmbg.setText("JMBG");

        jLabel_godina_prvog_razreda.setText("Godina prvog razreda");

        javax.swing.GroupLayout jInternalFrame_formularLayout = new javax.swing.GroupLayout(jInternalFrame_formular.getContentPane());
        jInternalFrame_formular.getContentPane().setLayout(jInternalFrame_formularLayout);
        jInternalFrame_formularLayout.setHorizontalGroup(
            jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_formularLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_formularLayout.createSequentialGroup()
                        .addComponent(jButton_Spremi_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Odustani_)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_formularLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jInternalFrame_formularLayout.createSequentialGroup()
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame_formularLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_ime)
                            .addComponent(jLabel_spol)
                            .addComponent(jLabel_prezime)
                            .addComponent(jLabel_imena_roditelja)
                            .addComponent(jLabel_datum_rodjenja)
                            .addComponent(jLabel_mjesto_rodjenja)
                            .addComponent(jLabel_opcina_rodjenja)
                            .addComponent(jLabel_drzava_rodjenja)
                            .addComponent(jLabel_drzavljanin)
                            .addComponent(jLabel_narodnost)
                            .addComponent(jLabel_jmbg))
                        .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame_formularLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jRadioButton_Spol_)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jInternalFrame_formularLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(txtIme))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_formularLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_formularLayout.createSequentialGroup()
                                        .addComponent(jRadioButton_Spol)
                                        .addGap(125, 125, 125))
                                    .addComponent(txtPrezime, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDatum_rodjenja, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtIme_roditelja, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMjesto_rodjenja, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtOpcina_rodjenja)
                                    .addComponent(txtDrzava_rodjenja, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDrzavljanin, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNarodnost, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtJmbg, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_formularLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_formularLayout.createSequentialGroup()
                                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_maticna_knjiga, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_maticni_broj, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_iducenik, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtidUcenika, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMaticni_broj)
                                    .addComponent(txtMaticna_knjiga, 0, 183, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_formularLayout.createSequentialGroup()
                                .addComponent(jLabel_godina_prvog_razreda)
                                .addGap(28, 28, 28)
                                .addComponent(txtGodina_prvog_razreda, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        jInternalFrame_formularLayout.setVerticalGroup(
            jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame_formularLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaticna_knjiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_maticna_knjiga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_maticni_broj)
                    .addComponent(txtMaticni_broj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidUcenika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_iducenik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ime)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_prezime)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_jmbg))
                .addGap(1, 1, 1)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_spol)
                    .addComponent(jRadioButton_Spol)
                    .addComponent(jRadioButton_Spol_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_imena_roditelja)
                    .addComponent(txtIme_roditelja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_datum_rodjenja)
                    .addComponent(txtDatum_rodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_mjesto_rodjenja)
                    .addComponent(txtMjesto_rodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame_formularLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel_opcina_rodjenja)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_formularLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOpcina_rodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDrzava_rodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_drzava_rodjenja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_drzavljanin)
                    .addComponent(txtDrzavljanin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNarodnost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_narodnost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGodina_prvog_razreda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_godina_prvog_razreda))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Spremi_)
                    .addComponent(jButton_Odustani_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_tablica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ID Učenika", "Matični knjiga", "Matični broj", "Ime", "Prezime"
            }
        ));
        jScrollPane1.setViewportView(jTable_tablica);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jInternalFrame_formular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame_formular)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Spremi_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Spremi_ActionPerformed
       
        try {
            String maticna_knjiga = txtMaticna_knjiga.getSelectedItem().toString();
            String maticni_broj = txtMaticni_broj.getText();
            String iducenik = txtidUcenika.getText();
            String ime = txtIme.getText();
            String prezime = txtPrezime.getText();
            String jmbg = txtJmbg.getText();
            String spol;
            if(jRadioButton_Spol.isSelected())
            {
                spol = "M";
            }
            else
            {
                spol = "Z";
            }
            String roditelj = txtIme_roditelja.getText();
            String datum_rodjenja = txtDatum_rodjenja.getText();
            String mjesto_rodjenja = txtMjesto_rodjenja.getText();
            String opcina_rodjenja = txtOpcina_rodjenja.getText();
            String drzava_rodjenja = txtDrzava_rodjenja.getSelectedItem().toString();
            String drzavljanstvo = txtDrzavljanin.getText();
            String nacionalnost = txtNarodnost.getSelectedItem().toString();
            String godina_prvog_razreda = txtGodina_prvog_razreda.getText();

            // TODO add your handling code here:

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ematicna_baza","root","");

            pst = con.prepareStatement("insert into ucenik(iducenik,maticna_knjiga,maticni_broj,ime,prezime,jmbg,spol,roditelj,datum_rodjenja,mjesto_rodjenja,opcina_rodjenja,drzava_rodjenja,drzavljanstvo,nacionalnost,godina_prvog_razreda)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

            pst.setString(1, iducenik);
            pst.setString(2, maticna_knjiga);
            pst.setString(3, maticni_broj);
            pst.setString(4, ime);
            pst.setString(5, prezime);
            pst.setString(6, jmbg);
            pst.setString(7, spol);
            pst.setString(8, roditelj);
            pst.setString(9, datum_rodjenja);
            pst.setString(10, mjesto_rodjenja);
            pst.setString(11, opcina_rodjenja);
            pst.setString(12, drzava_rodjenja);
            pst.setString(13, drzavljanstvo);
            pst.setString(14, nacionalnost);
            pst.setString(15, godina_prvog_razreda);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Dodan je novi učenik");
//  PONOVO UČITAJ STRANICU
            this.hide();
            Dodavanje_ucenika d_u = new Dodavanje_ucenika();
            d_u.setVisible(true);
//  POSTAVI PRAZNA POLJA
            txtidUcenika.setText("");
            txtMaticna_knjiga.setSelectedIndex(-1);
            txtMaticni_broj.setText("");
            txtIme.setText("");
            txtPrezime.setText("");
            txtJmbg.setText("");
            txtIme_roditelja.setText("");
            txtDatum_rodjenja.setText("");
            txtMjesto_rodjenja.setText("");
            txtOpcina_rodjenja.setText("");
            txtDrzava_rodjenja.setSelectedIndex(-1);
            txtDrzavljanin.setText("");
            txtNarodnost.setSelectedIndex(-1);
            txtGodina_prvog_razreda.setText("");
            txtidUcenika.requestFocus();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dodavanje_ucenika.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Dodavanje_ucenika.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_Spremi_ActionPerformed

    private void jButton_Odustani_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Odustani_ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton_Odustani_ActionPerformed

    private void txtIme_roditeljaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIme_roditeljaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIme_roditeljaActionPerformed

    private void txtDatum_rodjenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatum_rodjenjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatum_rodjenjaActionPerformed

    private void txtMaticna_knjigaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtMaticna_knjigaItemStateChanged
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ematicna_baza", "root", "");
            txtidUcenika.setText(txtMaticna_knjiga.getSelectedItem().toString()+txtMaticni_broj.getText() );

        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
            Logger.getLogger(Dodavanje_ucenika.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtMaticna_knjigaItemStateChanged

    private void txtMaticni_brojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaticni_brojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaticni_brojActionPerformed

    private void txtMaticni_brojKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaticni_brojKeyReleased
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ematicna_baza", "root", "");
            txtidUcenika.setText(txtMaticna_knjiga.getSelectedItem().toString()+txtMaticni_broj.getText() );

        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
            Logger.getLogger(Dodavanje_ucenika.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtMaticni_brojKeyReleased

    private void txtidUcenikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidUcenikaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidUcenikaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dodavanje_ucenika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dodavanje_ucenika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dodavanje_ucenika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dodavanje_ucenika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dodavanje_ucenika().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Odustani_;
    private javax.swing.JButton jButton_Spremi_;
    private javax.swing.JInternalFrame jInternalFrame_formular;
    private javax.swing.JLabel jLabel_datum_rodjenja;
    private javax.swing.JLabel jLabel_drzava_rodjenja;
    private javax.swing.JLabel jLabel_drzavljanin;
    private javax.swing.JLabel jLabel_godina_prvog_razreda;
    private javax.swing.JLabel jLabel_iducenik;
    private javax.swing.JLabel jLabel_ime;
    private javax.swing.JLabel jLabel_imena_roditelja;
    private javax.swing.JLabel jLabel_jmbg;
    private javax.swing.JLabel jLabel_maticna_knjiga;
    private javax.swing.JLabel jLabel_maticni_broj;
    private javax.swing.JLabel jLabel_mjesto_rodjenja;
    private javax.swing.JLabel jLabel_narodnost;
    private javax.swing.JLabel jLabel_opcina_rodjenja;
    private javax.swing.JLabel jLabel_prezime;
    private javax.swing.JLabel jLabel_spol;
    private javax.swing.JRadioButton jRadioButton_Spol;
    private javax.swing.JRadioButton jRadioButton_Spol_;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable_tablica;
    private javax.swing.JTextField txtDatum_rodjenja;
    private javax.swing.JComboBox txtDrzava_rodjenja;
    private javax.swing.JTextField txtDrzavljanin;
    private javax.swing.JTextField txtGodina_prvog_razreda;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtIme_roditelja;
    private javax.swing.JTextField txtJmbg;
    private javax.swing.JComboBox txtMaticna_knjiga;
    private javax.swing.JTextField txtMaticni_broj;
    private javax.swing.JTextField txtMjesto_rodjenja;
    private javax.swing.JComboBox txtNarodnost;
    private javax.swing.JTextField txtOpcina_rodjenja;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtidUcenika;
    // End of variables declaration//GEN-END:variables
}
