/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skola;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Severin
 */
public class Dodavanje_skolske_godine extends javax.swing.JFrame {
    
Connection con;
PreparedStatement pst;

    /**
     * Creates new form dodavanje_skolske_godine
     */
    public Dodavanje_skolske_godine() {
        initComponents();
        skolska_godina_tablica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_zaglavlje = new javax.swing.JPanel();
        jLabel_skolska_godina = new javax.swing.JLabel();
        jPanel_formular = new javax.swing.JPanel();
        jLabel_unesi_skolsku_godinu = new javax.swing.JLabel();
        txtGodina1 = new javax.swing.JTextField();
        jButton_Dodaj_ = new javax.swing.JButton();
        jButton_Odustani_ = new javax.swing.JButton();
        jLabel_20 = new javax.swing.JLabel();
        jLabel_kosa_crta = new javax.swing.JLabel();
        jLabel_20_ = new javax.swing.JLabel();
        txtGodina2 = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jButton_Obrisi_ = new javax.swing.JButton();
        jLabel_obrisi_godinu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane_tablica = new javax.swing.JScrollPane();
        jTable_tablica = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_zaglavlje.setBackground(new java.awt.Color(0, 153, 255));
        jPanel_zaglavlje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_skolska_godina.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_skolska_godina.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_skolska_godina.setText("Školska godina");

        javax.swing.GroupLayout jPanel_zaglavljeLayout = new javax.swing.GroupLayout(jPanel_zaglavlje);
        jPanel_zaglavlje.setLayout(jPanel_zaglavljeLayout);
        jPanel_zaglavljeLayout.setHorizontalGroup(
            jPanel_zaglavljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_zaglavljeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel_skolska_godina)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_zaglavljeLayout.setVerticalGroup(
            jPanel_zaglavljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_zaglavljeLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel_skolska_godina)
                .addGap(37, 37, 37))
        );

        jPanel_formular.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_formular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_unesi_skolsku_godinu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_unesi_skolsku_godinu.setText("Unesite školsku godinu ");

        jButton_Dodaj_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Dodaj_.setText("Dodaj");
        jButton_Dodaj_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Dodaj_ActionPerformed(evt);
            }
        });

        jButton_Odustani_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Odustani_.setText("Odustani");
        jButton_Odustani_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Odustani_ActionPerformed(evt);
            }
        });

        jLabel_20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_20.setText("20");

        jLabel_kosa_crta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_kosa_crta.setText("/");

        jLabel_20_.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_20_.setText("20");

        jButton_Obrisi_.setText("Obriši");
        jButton_Obrisi_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Obrisi_ActionPerformed(evt);
            }
        });

        jLabel_obrisi_godinu.setText("Obriši godinu:  ID");

        javax.swing.GroupLayout jPanel_formularLayout = new javax.swing.GroupLayout(jPanel_formular);
        jPanel_formular.setLayout(jPanel_formularLayout);
        jPanel_formularLayout.setHorizontalGroup(
            jPanel_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_formularLayout.createSequentialGroup()
                .addGroup(jPanel_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_formularLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_obrisi_godinu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Obrisi_)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_formularLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton_Dodaj_)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Odustani_))))
                    .addGroup(jPanel_formularLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel_unesi_skolsku_godinu)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel_20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGodina1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_kosa_crta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_20_, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGodina2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
            .addComponent(jSeparator1)
        );
        jPanel_formularLayout.setVerticalGroup(
            jPanel_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_formularLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_unesi_skolsku_godinu)
                    .addComponent(txtGodina1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_kosa_crta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_20_, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGodina2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Odustani_, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Dodaj_, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Obrisi_)
                    .addComponent(jLabel_obrisi_godinu))
                .addContainerGap())
        );

        jTable_tablica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Godina1", "Godina2"
            }
        ));
        jTable_tablica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_tablicaMouseClicked(evt);
            }
        });
        jScrollPane_tablica.setViewportView(jTable_tablica);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_zaglavlje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_formular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane_tablica, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_zaglavlje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_formular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane_tablica, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
// TABLICA: 
public void skolska_godina_tablica()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ematicna_baza","root",""); 
             
            pst = con.prepareStatement("select * from skolska_godina");
            ResultSet Rs = pst.executeQuery();
            
            ResultSetMetaData rd = Rs.getMetaData();
            int c = rd.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)jTable_tablica.getModel();
            df.setRowCount(0);
            
             while(Rs.next())
            {
               Vector v2 = new Vector();
               
               for(int i=1; i<c; i++)
               {   
                   v2.add(Rs.getString("id"));
                   v2.add(Rs.getString("godina1")); 
                   v2.add(Rs.getString("godina2")); 
               }
               df.addRow(v2);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dodavanje_skolske_godine.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Dodavanje_skolske_godine.class.getName()).log(Level.SEVERE, null, ex);
        }         
    }
    private void jButton_Dodaj_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Dodaj_ActionPerformed
        // TODO add your handling code here:

        String godina1 = txtGodina1.getText();
        String godina2 = txtGodina2.getText();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ematicna_baza","root","");

            pst = con.prepareStatement("insert into skolska_godina(godina1,godina2)values(?,?)");
            pst.setString(1, godina1);
            pst.setString(2, godina2);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Dodana je nova školska godina");
            txtGodina1.setText("");
            txtGodina2.setText("");
            txtGodina1.requestFocus();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dodavanje_skolske_godine.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Dodavanje_skolske_godine.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.hide();
        Dodavanje_skolske_godine d_s_g = new Dodavanje_skolske_godine();
        d_s_g.setVisible(true);
    }//GEN-LAST:event_jButton_Dodaj_ActionPerformed

    private void jButton_Odustani_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Odustani_ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton_Odustani_ActionPerformed

    private void jTable_tablicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_tablicaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel)jTable_tablica.getModel();
        int selectedIndex = jTable_tablica.getSelectedRow();

        txtid.setText(df.getValueAt(selectedIndex, 0).toString());
        
    }//GEN-LAST:event_jTable_tablicaMouseClicked

    private void jButton_Obrisi_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Obrisi_ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ematicna_baza", "root", "");

            pst = con.prepareStatement("delete from skolska_godina where id="+txtid.getText());

            pst.executeUpdate();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dodavanje_skolske_godine.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Dodavanje_skolske_godine.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.hide();
        Dodavanje_skolske_godine d_s_g = new Dodavanje_skolske_godine();
        d_s_g.setVisible(true);
    }//GEN-LAST:event_jButton_Obrisi_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dodavanje_skolske_godine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dodavanje_skolske_godine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dodavanje_skolske_godine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dodavanje_skolske_godine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dodavanje_skolske_godine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Dodaj_;
    private javax.swing.JButton jButton_Obrisi_;
    private javax.swing.JButton jButton_Odustani_;
    private javax.swing.JLabel jLabel_20;
    private javax.swing.JLabel jLabel_20_;
    private javax.swing.JLabel jLabel_kosa_crta;
    private javax.swing.JLabel jLabel_obrisi_godinu;
    private javax.swing.JLabel jLabel_skolska_godina;
    private javax.swing.JLabel jLabel_unesi_skolsku_godinu;
    private javax.swing.JPanel jPanel_formular;
    private javax.swing.JPanel jPanel_zaglavlje;
    private javax.swing.JScrollPane jScrollPane_tablica;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable_tablica;
    private javax.swing.JTextField txtGodina1;
    private javax.swing.JTextField txtGodina2;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
