/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skola;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Severin
 */
public class Maticni_podaci_korisnici extends javax.swing.JFrame {
Connection con;
PreparedStatement pst;
PreparedStatement pst1;
PreparedStatement pst2;
ResultSet rs;
    /**
     * Creates new form maticni_podaci
     */
    public Maticni_podaci_korisnici() {
        initComponents();
        maticna_knjiga();
        Connect();
    }
    
  public void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ematicna_baza", "root", "");

        } catch (ClassNotFoundException ex) {

        } catch (SQLException ex) {

        }
    }
    
    
    public void maticna_knjiga() {
     try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ematicna_baza","root","");    
            pst1 = con.prepareStatement("select * from maticna_knjiga");
            rs = pst1.executeQuery();
            
            txtMaticna_knjiga_padajuciizbornik.removeAllItems();
            
            while(rs.next())
            {
                txtMaticna_knjiga_padajuciizbornik.addItem(rs.getString(2));
            }
              
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Maticni_podaci_korisnici.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Maticni_podaci_korisnici.class.getName()).log(Level.SEVERE, null, ex);
        }     
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtMaticna_knjiga = new javax.swing.JTextField();
        txtMaticni_broj = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtSpol = new javax.swing.JTextField();
        txtRoditelj = new javax.swing.JTextField();
        txtDatum_rodjenja = new javax.swing.JTextField();
        txtMjesto_rodjenja = new javax.swing.JTextField();
        txtOpcina_rodjenja = new javax.swing.JTextField();
        txtDrzava_rodjenja = new javax.swing.JTextField();
        txtDrzavljanin = new javax.swing.JTextField();
        txtNarodnost = new javax.swing.JTextField();
        txtGodina_pocetka_skolovanja = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtJmbg = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        txtid_ = new javax.swing.JTextField();
        jButton_Pronadji_ucenika_ = new javax.swing.JButton();
        txtRazred_ = new javax.swing.JComboBox();
        txtMaticni_broj_ = new javax.swing.JTextField();
        txtMaticna_knjiga_padajuciizbornik = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtIzborni1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtNapomena = new javax.swing.JTextField();
        txtOpravdani = new javax.swing.JTextField();
        txtNeopravdani = new javax.swing.JTextField();
        txtMjesto = new javax.swing.JTextField();
        txtNadnevak = new javax.swing.JTextField();
        txtRavnatelj = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtUrbroj = new javax.swing.JTextField();
        txtJezik1o = new javax.swing.JTextField();
        txtLikovnakultura = new javax.swing.JTextField();
        txtGlazbenakultura = new javax.swing.JTextField();
        txtJezik2o = new javax.swing.JTextField();
        txtJezik3o = new javax.swing.JTextField();
        txtMatematika = new javax.swing.JTextField();
        txtPriroda = new javax.swing.JTextField();
        txtBiologija = new javax.swing.JTextField();
        txtKemija = new javax.swing.JTextField();
        txtFizika = new javax.swing.JTextField();
        txtPovijest = new javax.swing.JTextField();
        txtGeografija = new javax.swing.JTextField();
        txtTehnickakultura = new javax.swing.JTextField();
        txtTjelesni = new javax.swing.JTextField();
        txtPredmet1o = new javax.swing.JTextField();
        txtPredmet2o = new javax.swing.JTextField();
        txtPredmet3o = new javax.swing.JTextField();
        txtPredmet4o = new javax.swing.JTextField();
        txtIzborni1o = new javax.swing.JTextField();
        txtIzborni2o = new javax.swing.JTextField();
        txtIzborni3o = new javax.swing.JTextField();
        txtIzborni2 = new javax.swing.JTextField();
        txtIzborni3 = new javax.swing.JTextField();
        txtZavrsio = new javax.swing.JTextField();
        txtKojiput = new javax.swing.JTextField();
        txtVladanje = new javax.swing.JTextField();
        txtGodina = new javax.swing.JTextField();
        txtUspjeh = new javax.swing.JTextField();
        txtRazrednik = new javax.swing.JTextField();
        txtJezik1 = new javax.swing.JTextField();
        txtJezik2 = new javax.swing.JTextField();
        txtJezik3 = new javax.swing.JTextField();
        txtPredmet1 = new javax.swing.JTextField();
        txtPredmet2 = new javax.swing.JTextField();
        txtPredmet3 = new javax.swing.JTextField();
        txtPredmet4 = new javax.swing.JTextField();
        txtAktivnost1 = new javax.swing.JTextField();
        txtAktivnost2 = new javax.swing.JTextField();
        txtAktivnost3 = new javax.swing.JTextField();
        txtGodina1 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jButton_Odustani_ = new javax.swing.JButton();
        jButton_Novi_list_ = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Matični podaci ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel22.setText("Matična knjiga");

        jLabel30.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel30.setText("Matični broj");

        jLabel31.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel31.setText("Ime");

        jLabel32.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel32.setText("Prezime");

        jLabel33.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel33.setText("Spol");

        jLabel34.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel34.setText("Ime roditelja");

        jLabel35.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel35.setText("Datum rođenja");

        jLabel36.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel36.setText("Mjesto rođenja");

        jLabel37.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel37.setText("Općina rođenja");

        jLabel38.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel38.setText("Država rođenja");

        jLabel39.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel39.setText("Državljanin");

        jLabel40.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel40.setText("Narodnost");

        jLabel41.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel41.setText("Godina početka školovanja");

        txtMaticna_knjiga.setFont(new java.awt.Font("Calibri Light", 0, 10)); // NOI18N

        txtMaticni_broj.setFont(new java.awt.Font("Calibri Light", 0, 10)); // NOI18N

        txtIme.setFont(new java.awt.Font("Calibri Light", 0, 10)); // NOI18N

        txtPrezime.setFont(new java.awt.Font("Calibri Light", 0, 10)); // NOI18N

        txtSpol.setFont(new java.awt.Font("Calibri Light", 0, 10)); // NOI18N

        txtRoditelj.setFont(new java.awt.Font("Calibri Light", 0, 10)); // NOI18N

        txtDatum_rodjenja.setFont(new java.awt.Font("Calibri Light", 0, 10)); // NOI18N

        txtMjesto_rodjenja.setFont(new java.awt.Font("Calibri Light", 0, 10)); // NOI18N

        txtOpcina_rodjenja.setFont(new java.awt.Font("Calibri Light", 0, 10)); // NOI18N

        txtDrzava_rodjenja.setFont(new java.awt.Font("Calibri Light", 0, 10)); // NOI18N

        txtDrzavljanin.setFont(new java.awt.Font("Calibri Light", 0, 10)); // NOI18N

        txtNarodnost.setFont(new java.awt.Font("Calibri Light", 0, 10)); // NOI18N

        txtGodina_pocetka_skolovanja.setFont(new java.awt.Font("Calibri Light", 0, 10)); // NOI18N

        jLabel42.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel42.setText("JMBG");

        txtJmbg.setFont(new java.awt.Font("Calibri Light", 0, 10)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel43.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel43.setText("ID Učenika ");

        txtid_.setFont(new java.awt.Font("Calibri Light", 0, 10)); // NOI18N
        txtid_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid_ActionPerformed(evt);
            }
        });

        jButton_Pronadji_ucenika_.setBackground(new java.awt.Color(0, 153, 255));
        jButton_Pronadji_ucenika_.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 11)); // NOI18N
        jButton_Pronadji_ucenika_.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Pronadji_ucenika_.setText("Pronađi učenika");
        jButton_Pronadji_ucenika_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Pronadji_ucenika_ActionPerformed(evt);
            }
        });

        txtRazred_.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        txtRazred_.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtRazred_ItemStateChanged(evt);
            }
        });

        txtMaticni_broj_.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaticni_broj_KeyReleased(evt);
            }
        });

        txtMaticna_knjiga_padajuciizbornik.setToolTipText("\n\n");
        txtMaticna_knjiga_padajuciizbornik.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtMaticna_knjiga_padajuciizbornikItemStateChanged(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel21.setText("Matična knjiga");

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Matični broj");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Razred");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtid_)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtMaticna_knjiga_padajuciizbornik, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaticni_broj_, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRazred_, 0, 51, Short.MAX_VALUE)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jButton_Pronadji_ucenika_))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(13, 13, 13)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel44)
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRazred_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaticni_broj_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaticna_knjiga_padajuciizbornik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtid_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Pronadji_ucenika_, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel37)
                    .addComponent(jLabel36)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel34)
                        .addComponent(jLabel35)))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDatum_rodjenja)
                    .addComponent(txtRoditelj)
                    .addComponent(txtMjesto_rodjenja, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtOpcina_rodjenja, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel38)
                .addGap(23, 23, 23)
                .addComponent(txtDrzava_rodjenja))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel39)
                .addGap(41, 41, 41)
                .addComponent(txtDrzavljanin))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel40)
                .addGap(44, 44, 44)
                .addComponent(txtNarodnost))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtGodina_pocetka_skolovanja, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addGap(66, 66, 66)
                        .addComponent(txtJmbg))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(72, 72, 72)
                        .addComponent(txtSpol))))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrezime)
                    .addComponent(txtIme)
                    .addComponent(txtMaticni_broj, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaticna_knjiga)))
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtMaticna_knjiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaticni_broj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txtJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSpol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtRoditelj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtDatum_rodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txtMjesto_rodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(txtOpcina_rodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(txtDrzava_rodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txtDrzavljanin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txtNarodnost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(txtGodina_pocetka_skolovanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("DIPLOMA - Predmeti i ocjene po redoslijedu sa svjedodžbe"));

        jLabel3.setText("Likovna kultura");

        jLabel2.setText("Glazbena kultura");

        jLabel4.setText("Matematika");

        jLabel5.setText("Priroda ");

        jLabel6.setText("Biologija");

        jLabel7.setText("Kemija");

        jLabel8.setText("Fizika");

        jLabel9.setText("Povijest");

        jLabel10.setText("Geografija");

        jLabel11.setText("Tehnička kultura");

        jLabel12.setText("Tjelesna i zdravstvena kultura");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Izborni predmeti");

        jLabel14.setText("Završio - la");

        jLabel15.setText("Koji put ");

        jLabel16.setText("Vladanje");

        jLabel17.setText("Opći uspjeh");

        jLabel18.setText("Opravdani izostanci");

        jLabel19.setText("Neopravdani izostanci");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Izvannastavne i izvanškolske aktivnosti ");

        jLabel23.setText("U mjestu ");

        jLabel24.setText("Nadnevak");

        jLabel25.setText("Razrednik");

        jLabel26.setText("Ravnatelj");

        jLabel27.setText("Napomena");

        txtMjesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMjestoActionPerformed(evt);
            }
        });

        txtNadnevak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNadnevakActionPerformed(evt);
            }
        });

        txtRavnatelj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRavnateljActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel28.setText("Školska godina");

        jLabel29.setText("Urudžbeni broj");

        txtRazrednik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazrednikActionPerformed(evt);
            }
        });

        txtGodina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGodina1ActionPerformed(evt);
            }
        });

        jLabel46.setText("/");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNapomena))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtJezik1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(0, 23, Short.MAX_VALUE))
                            .addComponent(txtJezik2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtJezik3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtJezik1o, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLikovnakultura, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGlazbenakultura, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtFizika, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPovijest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtKemija, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBiologija, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPriroda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMatematika, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJezik3o, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJezik2o, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtIzborni1)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtIzborni2)
                                        .addComponent(txtIzborni3)
                                        .addComponent(txtPredmet1)
                                        .addComponent(txtPredmet2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPredmet3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPredmet4, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTjelesni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPredmet1o, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPredmet2o, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPredmet3o, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPredmet4o, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtIzborni1o, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtIzborni2o, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtIzborni3o, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTehnickakultura, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtGeografija, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMjesto)
                                    .addComponent(txtNadnevak, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtRazrednik)))
                            .addComponent(txtAktivnost1)
                            .addComponent(txtAktivnost2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAktivnost3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel28))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtGodina, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtGodina1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 68, Short.MAX_VALUE))
                                    .addComponent(txtUrbroj)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addGap(71, 71, 71)
                                        .addComponent(txtRavnatelj))
                                    .addComponent(jLabel20)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                    .addComponent(jLabel18)
                                                    .addGap(26, 26, 26))
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                    .addComponent(jLabel19)
                                                    .addGap(15, 15, 15)))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel16)
                                                    .addComponent(jLabel17))
                                                .addGap(64, 64, 64)))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtZavrsio)
                                            .addComponent(txtKojiput)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtNeopravdani, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtOpravdani, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 102, Short.MAX_VALUE))
                                            .addComponent(txtVladanje)
                                            .addComponent(txtUspjeh))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(jSeparator2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14)
                            .addComponent(txtJezik1o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGeografija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtZavrsio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJezik1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15)
                            .addComponent(txtLikovnakultura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTehnickakultura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKojiput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16)
                            .addComponent(txtGlazbenakultura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTjelesni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVladanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtJezik2o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPredmet1o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUspjeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJezik2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPredmet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtOpravdani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJezik3o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPredmet2o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJezik3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPredmet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel19)
                            .addComponent(txtNeopravdani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMatematika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPredmet3o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPredmet3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel20)
                            .addComponent(txtPriroda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPredmet4o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPredmet4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtBiologija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(txtAktivnost1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txtKemija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIzborni1o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIzborni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAktivnost2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(txtFizika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIzborni2o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIzborni2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAktivnost3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtPovijest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel28)
                                    .addComponent(txtGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGodina1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel46)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIzborni3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIzborni3o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtUrbroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtMjesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtNadnevak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtRazrednik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtRavnatelj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtNapomena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jButton_Odustani_.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Odustani_.setText("Odustani");
        jButton_Odustani_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Odustani_ActionPerformed(evt);
            }
        });

        jButton_Novi_list_.setText("Novi list ");
        jButton_Novi_list_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Novi_list_ActionPerformed(evt);
            }
        });

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_Novi_list_)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Odustani_)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Novi_list_, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Odustani_, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel4.getAccessibleContext().setAccessibleName("DIPLOMA");

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Matična knjiga");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtid_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid_ActionPerformed

    private void jButton_Pronadji_ucenika_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Pronadji_ucenika_ActionPerformed
        try {
            pst = con.prepareStatement("select id,iducenik,maticna_knjiga,maticni_broj,ime,prezime,jmbg,spol,roditelj,datum_rodjenja,mjesto_rodjenja,opcina_rodjenja,drzava_rodjenja,drzavljanstvo,nacionalnost,godina_prvog_razreda from ucenik where iducenik=?");
            int iducenik = Integer.parseInt(txtid_.getText());
            pst.setInt(1, iducenik);
            ResultSet rs1 = pst.executeQuery();
            if (rs1.next() == false) {
                JOptionPane.showMessageDialog(this, "Učenik nije pronađen");
                txtMaticna_knjiga.setText("");
                txtMaticni_broj.setText("");
                txtIme.setText("");
                txtPrezime.setText("");
                txtJmbg.setText("");
                txtSpol.setText("");
                txtRoditelj.setText("");
                txtDatum_rodjenja.setText("");
                txtMjesto_rodjenja.setText("");
                txtOpcina_rodjenja.setText("");
                txtDrzava_rodjenja.setText("");
                txtDrzavljanin.setText("");
                txtNarodnost.setText("");
                txtGodina_pocetka_skolovanja.setText("");
                txtid_.requestFocus();
            } else {
                txtMaticna_knjiga.setText(rs1.getString("maticna_knjiga"));
                txtMaticni_broj.setText(rs1.getString("maticni_broj"));
                txtIme.setText(rs1.getString("ime"));
                txtPrezime.setText(rs1.getString("prezime"));
                txtJmbg.setText(rs1.getString("jmbg"));
                txtSpol.setText(rs1.getString("spol"));
                txtRoditelj.setText(rs1.getString("roditelj"));
                txtDatum_rodjenja.setText(rs1.getString("datum_rodjenja"));
                txtMjesto_rodjenja.setText(rs1.getString("mjesto_rodjenja"));
                txtOpcina_rodjenja.setText(rs1.getString("opcina_rodjenja"));
                txtDrzava_rodjenja.setText(rs1.getString("drzava_rodjenja"));
                txtDrzavljanin.setText(rs1.getString("drzavljanstvo"));
                txtNarodnost.setText(rs1.getString("nacionalnost"));
                txtGodina_pocetka_skolovanja.setText(rs1.getString("godina_prvog_razreda"));

            }

        } catch (SQLException ex) {
            Logger.getLogger(Maticni_podaci_korisnici.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Ocjene
        try {
            pst = con.prepareStatement("select id,iducenik,jezik1,jezik1o,likovnakultura,glazbenakultura,jezik2,jezik2o,jezik3,jezik3o,matematika,priroda,biologija,kemija,fizika,povijest,geografija,tehnickakultura,tjelesni,predmet1,predmet1o,predmet2,predmet2o,predmet3,predmet3o,predmet4,predmet4o,izborni1,izborni1o,izborni2,izborni2o,izborni3,izborni3o from maticni_podaci_1 where iducenik=?");
            int iducenik = Integer.parseInt(txtid_.getText()+txtRazred_.getSelectedItem().toString());
            pst.setInt(1, iducenik);
            ResultSet rs1 = pst.executeQuery();
            if (rs1.next() == false) {
                JOptionPane.showMessageDialog(this, "Učenik nije pohađao navedeni razred");
                
                txtJezik1.setText("");
                txtJezik1o.setText("");
                txtLikovnakultura.setText("");
                txtGlazbenakultura.setText("");
                txtJezik2.setText("");
                txtJezik2o.setText("");
                txtJezik3.setText("");
                txtJezik3o.setText("");
                txtMatematika.setText("");
                txtPriroda.setText("");
                txtBiologija.setText("");
                txtKemija.setText("");
                txtFizika.setText("");
                txtPovijest.setText("");
                txtGeografija.setText("");
                txtTehnickakultura.setText("");
                txtTjelesni.setText("");
                txtPredmet1.setText("");
                txtPredmet1o.setText("");
                txtPredmet2.setText("");
                txtPredmet2o.setText("");
                txtPredmet3.setText("");
                txtPredmet3o.setText("");
                txtPredmet4.setText("");
                txtPredmet4o.setText("");
                txtIzborni1.setText("");
                txtIzborni1o.setText("");
                txtIzborni2.setText("");
                txtIzborni2o.setText("");
                txtIzborni3.setText("");
                txtIzborni3o.setText("");
                txtid_.requestFocus();
            } else {
               
                txtJezik1.setText(rs1.getString("jezik1"));
                txtJezik1o.setText(rs1.getString("jezik1o"));
                txtLikovnakultura.setText(rs1.getString("likovnakultura"));
                txtGlazbenakultura.setText(rs1.getString("glazbenakultura"));
                txtJezik2.setText(rs1.getString("jezik2"));
                txtJezik2o.setText(rs1.getString("jezik2o"));
                txtJezik3.setText(rs1.getString("jezik3"));
                txtJezik3o.setText(rs1.getString("jezik3o"));
                txtMatematika.setText(rs1.getString("matematika"));
                txtPriroda.setText(rs1.getString("priroda"));
                txtBiologija.setText(rs1.getString("biologija"));
                txtKemija.setText(rs1.getString("kemija"));
                txtFizika.setText(rs1.getString("fizika"));
                txtPovijest.setText(rs1.getString("povijest"));
                txtGeografija.setText(rs1.getString("geografija"));
                txtTehnickakultura.setText(rs1.getString("tehnickakultura"));
                txtTjelesni.setText(rs1.getString("tjelesni"));
                txtPredmet1.setText(rs1.getString("predmet1"));
                txtPredmet1o.setText(rs1.getString("predmet1o"));
                txtPredmet2.setText(rs1.getString("predmet2"));
                txtPredmet2o.setText(rs1.getString("predmet2o"));
                txtPredmet3.setText(rs1.getString("predmet3"));
                txtPredmet3o.setText(rs1.getString("predmet3o"));
                txtPredmet4.setText(rs1.getString("predmet4"));
                txtPredmet4o.setText(rs1.getString("predmet4o"));
                txtIzborni1.setText(rs1.getString("izborni1"));
                txtIzborni1o.setText(rs1.getString("izborni1o"));
                txtIzborni2.setText(rs1.getString("izborni2"));
                txtIzborni2o.setText(rs1.getString("izborni2o"));
                txtIzborni3.setText(rs1.getString("izborni3"));
                txtIzborni3o.setText(rs1.getString("izborni3o"));

            }

        } catch (SQLException ex) {
            Logger.getLogger(Maticni_podaci_korisnici.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Ostalo
        try {
            pst = con.prepareStatement("select id,iducenik,zavrsio,kojiput,vladanje,uspjeh,opravdani,neopravdani,aktivnost1,aktivnost2,aktivnost3,godina1,godina2,urbroj,mjesto,nadnevak,razrednik,ravnatelj,napomena from maticni_podaci_2 where iducenik=?");
            int iducenik = Integer.parseInt(txtid_.getText()+txtRazred_.getSelectedItem().toString());
            pst.setInt(1, iducenik);
            ResultSet rs1 = pst.executeQuery();

            if (rs1.next() == false) {
                txtZavrsio.setText("");
                txtKojiput.setText("");
                txtVladanje.setText("");
                txtUspjeh.setText("");
                txtOpravdani.setText("");
                txtNeopravdani.setText("");
                txtAktivnost1.setText("");
                txtAktivnost2.setText("");
                txtAktivnost3.setText("");
                txtGodina.setText("");
                txtGodina1.setText("");
                txtUrbroj.setText("");
                txtMjesto.setText("");
                txtNadnevak.setText("");
                txtRazrednik.setText("");
                txtRavnatelj.setText("");
                txtNapomena.setText("");

                txtid_.requestFocus();
            } else {

                txtZavrsio.setText(rs1.getString("zavrsio"));
                txtKojiput.setText(rs1.getString("kojiput"));
                txtVladanje.setText(rs1.getString("vladanje"));
                txtUspjeh.setText(rs1.getString("uspjeh"));
                txtOpravdani.setText(rs1.getString("opravdani"));
                txtNeopravdani.setText(rs1.getString("neopravdani"));
                txtAktivnost1.setText(rs1.getString("aktivnost1"));
                txtAktivnost2.setText(rs1.getString("aktivnost2"));
                txtAktivnost3.setText(rs1.getString("aktivnost3"));
                txtGodina.setText(rs1.getString("godina1"));
                txtGodina1.setText(rs1.getString("godina2"));
                txtUrbroj.setText(rs1.getString("urbroj"));
                txtMjesto.setText(rs1.getString("mjesto"));
                txtNadnevak.setText(rs1.getString("nadnevak"));
                txtRazrednik.setText(rs1.getString("razrednik"));
                txtRavnatelj.setText(rs1.getString("ravnatelj"));
                txtNapomena.setText(rs1.getString("napomena"));

            }

        } catch (SQLException ex) {
            Logger.getLogger(Maticni_podaci_korisnici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_Pronadji_ucenika_ActionPerformed

    private void txtRazred_ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtRazred_ItemStateChanged
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ematicna_baza", "root", "");
            txtid_.setText(txtMaticna_knjiga_padajuciizbornik.getSelectedItem().toString()+txtMaticni_broj_.getText() );

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Maticni_podaci_korisnici.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Maticni_podaci_korisnici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtRazred_ItemStateChanged

    private void txtMaticni_broj_KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaticni_broj_KeyReleased
        // TODO add your handling code here:

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ematicna_baza", "root", "");
            txtid_.setText(txtMaticna_knjiga_padajuciizbornik.getSelectedItem().toString()+txtMaticni_broj_.getText() );

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Maticni_podaci_korisnici.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Maticni_podaci_korisnici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtMaticni_broj_KeyReleased

    private void txtMaticna_knjiga_padajuciizbornikItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtMaticna_knjiga_padajuciizbornikItemStateChanged
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ematicna_baza", "root", "");
            txtid_.setText(txtMaticna_knjiga_padajuciizbornik.getSelectedItem().toString()+txtMaticni_broj_.getText() );

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Maticni_podaci_korisnici.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Maticni_podaci_korisnici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtMaticna_knjiga_padajuciizbornikItemStateChanged

    private void txtMjestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMjestoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtMjestoActionPerformed

    private void txtNadnevakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNadnevakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNadnevakActionPerformed

    private void txtRavnateljActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRavnateljActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRavnateljActionPerformed

    private void txtRazrednikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazrednikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazrednikActionPerformed

    private void txtGodina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGodina1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGodina1ActionPerformed

    private void jButton_Odustani_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Odustani_ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton_Odustani_ActionPerformed

    private void jButton_Novi_list_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Novi_list_ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Maticni_podaci_korisnici m_p = new Maticni_podaci_korisnici();
        m_p.setVisible(true);
    }//GEN-LAST:event_jButton_Novi_list_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maticni_podaci_korisnici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maticni_podaci_korisnici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maticni_podaci_korisnici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maticni_podaci_korisnici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maticni_podaci_korisnici().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Novi_list_;
    private javax.swing.JButton jButton_Odustani_;
    private javax.swing.JButton jButton_Pronadji_ucenika_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField txtAktivnost1;
    private javax.swing.JTextField txtAktivnost2;
    private javax.swing.JTextField txtAktivnost3;
    private javax.swing.JTextField txtBiologija;
    private javax.swing.JTextField txtDatum_rodjenja;
    private javax.swing.JTextField txtDrzava_rodjenja;
    private javax.swing.JTextField txtDrzavljanin;
    private javax.swing.JTextField txtFizika;
    private javax.swing.JTextField txtGeografija;
    private javax.swing.JTextField txtGlazbenakultura;
    private javax.swing.JTextField txtGodina;
    private javax.swing.JTextField txtGodina1;
    private javax.swing.JTextField txtGodina_pocetka_skolovanja;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtIzborni1;
    private javax.swing.JTextField txtIzborni1o;
    private javax.swing.JTextField txtIzborni2;
    private javax.swing.JTextField txtIzborni2o;
    private javax.swing.JTextField txtIzborni3;
    private javax.swing.JTextField txtIzborni3o;
    private javax.swing.JTextField txtJezik1;
    private javax.swing.JTextField txtJezik1o;
    private javax.swing.JTextField txtJezik2;
    private javax.swing.JTextField txtJezik2o;
    private javax.swing.JTextField txtJezik3;
    private javax.swing.JTextField txtJezik3o;
    private javax.swing.JTextField txtJmbg;
    private javax.swing.JTextField txtKemija;
    private javax.swing.JTextField txtKojiput;
    private javax.swing.JTextField txtLikovnakultura;
    private javax.swing.JTextField txtMatematika;
    private javax.swing.JTextField txtMaticna_knjiga;
    private javax.swing.JComboBox txtMaticna_knjiga_padajuciizbornik;
    private javax.swing.JTextField txtMaticni_broj;
    private javax.swing.JTextField txtMaticni_broj_;
    private javax.swing.JTextField txtMjesto;
    private javax.swing.JTextField txtMjesto_rodjenja;
    private javax.swing.JTextField txtNadnevak;
    private javax.swing.JTextField txtNapomena;
    private javax.swing.JTextField txtNarodnost;
    private javax.swing.JTextField txtNeopravdani;
    private javax.swing.JTextField txtOpcina_rodjenja;
    private javax.swing.JTextField txtOpravdani;
    private javax.swing.JTextField txtPovijest;
    private javax.swing.JTextField txtPredmet1;
    private javax.swing.JTextField txtPredmet1o;
    private javax.swing.JTextField txtPredmet2;
    private javax.swing.JTextField txtPredmet2o;
    private javax.swing.JTextField txtPredmet3;
    private javax.swing.JTextField txtPredmet3o;
    private javax.swing.JTextField txtPredmet4;
    private javax.swing.JTextField txtPredmet4o;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtPriroda;
    private javax.swing.JTextField txtRavnatelj;
    private javax.swing.JComboBox txtRazred_;
    private javax.swing.JTextField txtRazrednik;
    private javax.swing.JTextField txtRoditelj;
    private javax.swing.JTextField txtSpol;
    private javax.swing.JTextField txtTehnickakultura;
    private javax.swing.JTextField txtTjelesni;
    private javax.swing.JTextField txtUrbroj;
    private javax.swing.JTextField txtUspjeh;
    private javax.swing.JTextField txtVladanje;
    private javax.swing.JTextField txtZavrsio;
    private javax.swing.JTextField txtid_;
    // End of variables declaration//GEN-END:variables
}
