/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skola;

/**
 *
 * @author Severin
 */
public class Oprogramu extends javax.swing.JFrame {

    /**
     * Creates new form oprogrami
     */
    public Oprogramu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_pozadina = new javax.swing.JPanel();
        jPanel_zaglavlje = new javax.swing.JPanel();
        jLabel_oprogramu = new javax.swing.JLabel();
        jButton_Zatvori_ = new javax.swing.JButton();
        jScrollPane_text = new javax.swing.JScrollPane();
        jTextArea_text = new javax.swing.JTextArea();
        jLabel_eMaticna_knjiga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_pozadina.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_pozadina.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel_zaglavlje.setBackground(new java.awt.Color(0, 153, 255));
        jPanel_zaglavlje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_oprogramu.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel_oprogramu.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_oprogramu.setText("O programu");

        jButton_Zatvori_.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Zatvori_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Zatvori_.setText("Zatvori");
        jButton_Zatvori_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Zatvori_MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_zaglavljeLayout = new javax.swing.GroupLayout(jPanel_zaglavlje);
        jPanel_zaglavlje.setLayout(jPanel_zaglavljeLayout);
        jPanel_zaglavljeLayout.setHorizontalGroup(
            jPanel_zaglavljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_zaglavljeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_oprogramu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(jButton_Zatvori_, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_zaglavljeLayout.setVerticalGroup(
            jPanel_zaglavljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_zaglavljeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel_zaglavljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_oprogramu)
                    .addComponent(jButton_Zatvori_, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTextArea_text.setEditable(false);
        jTextArea_text.setColumns(20);
        jTextArea_text.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jTextArea_text.setRows(5);
        jTextArea_text.setText("\tPROJEKT ZA DIPLOMSKI RAD \n\n       RAZVOJ PROGRAMSKOG RJEŠENJA ZA EVIDENCIJU\n              NASTAVE U PROGRAMSKOM JEZIKU JAVA\n\nE-Matična knjiga je centralizirani sustav koji služi za unos\n najvažnijih podataka o učenicima i djelatnicima osnovnih i\n srednjih škola. Aplikacija je zamišljena kao digitalni oblik\n Matične knjige koja se u školama ručno ispunjava.\n Korisnici se prijavljuju pomoću podataka dobivenih od\n odgovorne osobe zadužene za nadzor i informatičku podršku.\nNajvažnije prednosti sustava u odnosu na ručni unos podataka\n su te što su ovim načinom podaci dostupni s bilo koje lokacije\n koja je povezana na Internet.\n\nKARAKTERISTIKE eMatične knjige:\n\nBaza podataka\n-MySql baza\n-Naziv: ematicna_baza\n-8 tablica u bazi:\n\t1. admin\n\t2. korisnik\n\t3. maticna_knjiga\n\t4. maticni_podaci_1\n\t5. maticni_podaci_2\n\t6. razred\n\t7. skolska_godina\n\t8. ucenik\n \nSučelje\n- 18 Prozora:\n\t•Prozor “Pocetna”\n\t•Prozor “Prijava_korisnik”\n\t•Prozor “Prijava_admin”\n\t•Prozor “Sucelje_korisnik”\n\t•Prozor “Sucelje_admin”\n\t•Prozor “Dodavanje_korisnika”\n\t•Prozor “Dodavanje_admina”\n\t•Prozor “Dodavanje_ucenika”\n\t•Prozor “Dodavanje_razred”\n\t•Prozor “Dodavanje_maticne_knjige”\n\t•Prozor “Dodavanje_skolske_godine”\n\t•Prozor “Popis_ucenika”\t\n\t•Prozor “Popis_ucenik_uredjivanje”\n\t•Prozor “Ucenik_uredjivanje”\n\t•Prozor “Upis_maticni_podaci”\n\t•Prozor “Maticni_podaci”\n\t•Prozor „Maticni_podaci_korisnici“\n\t•Prozor “Oprogramu”\n\nKorisnici sustava:\n\t1. Korisnici\n\t2. Administratori\n\nPodaci za prijavu:\n\t1. Korisnici: \n\t \tKorisnicko ime \n\t\tLozinka\n\n\t2. Administratori \n\t\tAdmin ime \n\t\tAdmin lozinka\n\t\n___________________________________________________________\n\n\t\tAutor: \n\t\tSeverin Knežević\n\t\temail: severinknezevic@gmail.com\n\t\tkontakt broj: 063/619-978\n\n\t\tStudent \n\t\tBroj indeksa: 3646/ds\n\t\tStudiji informatike\n\t\tSveučilište u Mostaru\t");
        jScrollPane_text.setViewportView(jTextArea_text);

        jLabel_eMaticna_knjiga.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel_eMaticna_knjiga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_eMaticna_knjiga.setText("eMatična knjiga");

        javax.swing.GroupLayout jPanel_pozadinaLayout = new javax.swing.GroupLayout(jPanel_pozadina);
        jPanel_pozadina.setLayout(jPanel_pozadinaLayout);
        jPanel_pozadinaLayout.setHorizontalGroup(
            jPanel_pozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_zaglavlje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_pozadinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_pozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_eMaticna_knjiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane_text, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel_pozadinaLayout.setVerticalGroup(
            jPanel_pozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_pozadinaLayout.createSequentialGroup()
                .addComponent(jPanel_zaglavlje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel_eMaticna_knjiga)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane_text, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_pozadina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_pozadina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Zatvori_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Zatvori_MouseClicked
    // TODO add your handling code here:
    this.hide();
    }//GEN-LAST:event_jButton_Zatvori_MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Oprogramu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Oprogramu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Oprogramu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Oprogramu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Oprogramu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Zatvori_;
    private javax.swing.JLabel jLabel_eMaticna_knjiga;
    private javax.swing.JLabel jLabel_oprogramu;
    private javax.swing.JPanel jPanel_pozadina;
    private javax.swing.JPanel jPanel_zaglavlje;
    private javax.swing.JScrollPane jScrollPane_text;
    private javax.swing.JTextArea jTextArea_text;
    // End of variables declaration//GEN-END:variables
}
