/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skola;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Severin
 */
public class Prijava_admin extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form prijava_admin
     */
    public Prijava_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1_pozadina = new javax.swing.JPanel();
        jPanel2_zaglavlje = new javax.swing.JPanel();
        jLabel1_administracija = new javax.swing.JLabel();
        jButton3_korisnicka_prijava_ = new javax.swing.JButton();
        jLabel4_prijava = new javax.swing.JLabel();
        jLabel2_admin_ime = new javax.swing.JLabel();
        jLabel3_admin_lozinka = new javax.swing.JLabel();
        txtAdmin_ime = new javax.swing.JTextField();
        txtLozinka = new javax.swing.JPasswordField();
        jButton_prijava_ = new javax.swing.JButton();
        jButton_odustani_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1_pozadina.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1_pozadina.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2_zaglavlje.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2_zaglavlje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1_administracija.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel1_administracija.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_administracija.setText("Administracija");

        jButton3_korisnicka_prijava_.setBackground(new java.awt.Color(204, 204, 204));
        jButton3_korisnicka_prijava_.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton3_korisnicka_prijava_.setText("Korisnička prijava");
        jButton3_korisnicka_prijava_.setAutoscrolls(true);
        jButton3_korisnicka_prijava_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_korisnicka_prijava_ActionPerformed(evt);
            }
        });

        jLabel4_prijava.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel4_prijava.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4_prijava.setText("Prijava");

        javax.swing.GroupLayout jPanel2_zaglavljeLayout = new javax.swing.GroupLayout(jPanel2_zaglavlje);
        jPanel2_zaglavlje.setLayout(jPanel2_zaglavljeLayout);
        jPanel2_zaglavljeLayout.setHorizontalGroup(
            jPanel2_zaglavljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_zaglavljeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_administracija, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton3_korisnicka_prijava_)
                .addContainerGap())
            .addGroup(jPanel2_zaglavljeLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel4_prijava)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2_zaglavljeLayout.setVerticalGroup(
            jPanel2_zaglavljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_zaglavljeLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2_zaglavljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_administracija, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3_korisnicka_prijava_, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4_prijava, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2_admin_ime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2_admin_ime.setText("Admin ime ");

        jLabel3_admin_lozinka.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3_admin_lozinka.setText("Admin Lozinka");

        txtAdmin_ime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdmin_imeActionPerformed(evt);
            }
        });

        jButton_prijava_.setBackground(new java.awt.Color(255, 255, 255));
        jButton_prijava_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_prijava_.setText("Prijavi se");
        jButton_prijava_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_prijava_ActionPerformed(evt);
            }
        });

        jButton_odustani_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_odustani_.setText("Odustani");
        jButton_odustani_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_odustani_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1_pozadinaLayout = new javax.swing.GroupLayout(jPanel1_pozadina);
        jPanel1_pozadina.setLayout(jPanel1_pozadinaLayout);
        jPanel1_pozadinaLayout.setHorizontalGroup(
            jPanel1_pozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2_zaglavlje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1_pozadinaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1_pozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2_admin_ime)
                    .addComponent(jLabel3_admin_lozinka))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1_pozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1_pozadinaLayout.createSequentialGroup()
                        .addComponent(jButton_prijava_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_odustani_))
                    .addGroup(jPanel1_pozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAdmin_ime, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1_pozadinaLayout.setVerticalGroup(
            jPanel1_pozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_pozadinaLayout.createSequentialGroup()
                .addComponent(jPanel2_zaglavlje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1_pozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_admin_ime)
                    .addComponent(txtAdmin_ime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1_pozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3_admin_lozinka)
                    .addComponent(txtLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1_pozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_prijava_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_odustani_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_pozadina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_pozadina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3_korisnicka_prijava_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_korisnicka_prijava_ActionPerformed
        // TODO add your handling code here:
        Prijava_korisnik p_k = new Prijava_korisnik();
        this.hide();
        p_k.setVisible(true);
    }//GEN-LAST:event_jButton3_korisnicka_prijava_ActionPerformed

    private void txtAdmin_imeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdmin_imeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdmin_imeActionPerformed

    private void jButton_prijava_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_prijava_ActionPerformed

        try {

            if(txtAdmin_ime.getText().isEmpty() || txtLozinka.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Niste unijeli sve podatke");
            }
            else
            {
                String admin_ime = txtAdmin_ime.getText();
                String lozinka = txtLozinka.getText();

                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/ematicna_baza","root","");
                pst = con.prepareStatement("select * from admin where admin_ime= ? and lozinka=? ");
                pst.setString(1, admin_ime);
                pst.setString(2, lozinka);
                rs = pst.executeQuery();

                if(rs.next())
                {
                    Sucelje_admin s_a = new Sucelje_admin();
                    this.hide();
                    s_a.setVisible(true);
/** Prijavljeni administrator u sučelju aplikacije **/ 
                    s_a.admin_ime(admin_ime);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Korisnički podaci nisu valjani");
                    txtAdmin_ime.setText("");
                    txtLozinka.setText("");
                    txtAdmin_ime.requestFocus();
                }

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Prijava_admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Prijava_admin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_prijava_ActionPerformed

    private void jButton_odustani_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_odustani_ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_odustani_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prijava_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prijava_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prijava_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prijava_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prijava_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3_korisnicka_prijava_;
    private javax.swing.JButton jButton_odustani_;
    private javax.swing.JButton jButton_prijava_;
    private javax.swing.JLabel jLabel1_administracija;
    private javax.swing.JLabel jLabel2_admin_ime;
    private javax.swing.JLabel jLabel3_admin_lozinka;
    private javax.swing.JLabel jLabel4_prijava;
    private javax.swing.JPanel jPanel1_pozadina;
    private javax.swing.JPanel jPanel2_zaglavlje;
    private javax.swing.JTextField txtAdmin_ime;
    private javax.swing.JPasswordField txtLozinka;
    // End of variables declaration//GEN-END:variables
}
