/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skola;

/**
 *
 * @author Severin
 */
public class Sucelje_admin extends javax.swing.JFrame {

    /**
     * Creates new form sucelje_admin
     */
    public Sucelje_admin() {
        initComponents();
//      setLocationRelativeTo(null);
    }
    
    
   void admin_ime (String admin_ime){
   ime_prijavljenog_administratora.setText(admin_ime);
   }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_pozadina = new javax.swing.JPanel();
        jPanel_zaglavlje = new javax.swing.JPanel();
        jLabel_eMaticna_knjiga_ = new javax.swing.JLabel();
        jButton_Odjavi_se_ = new javax.swing.JButton();
        jLabel_administracija = new javax.swing.JLabel();
        ime_prijavljenog_administratora = new javax.swing.JLabel();
        jLabel_administrator = new javax.swing.JLabel();
        jPanel_podnozje = new javax.swing.JPanel();
        jLabel_autor = new javax.swing.JLabel();
        jButton_Oprogramu_ = new javax.swing.JButton();
        jPanel_izbornik = new javax.swing.JPanel();
        jButton_Upravljaj_korisnicima_ = new javax.swing.JButton();
        jButton_Dodaj_novog_ucenika_ = new javax.swing.JButton();
        jButton_Upis_u_maticnu_knjigu_ = new javax.swing.JButton();
        jButton_Dodaj_novu_skolsku_godinu_ = new javax.swing.JButton();
        jButton_Upravljaj_administratorima_ = new javax.swing.JButton();
        jButton_Evidencija_ucenika_ = new javax.swing.JButton();
        jButton_Dodaj_novi_razred_ = new javax.swing.JButton();
        jButton_Dodaj_novu_maticnu_knjigu_ = new javax.swing.JButton();
        jButton_Maticni_podaci_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_pozadina.setBackground(new java.awt.Color(204, 204, 204));

        jPanel_zaglavlje.setBackground(new java.awt.Color(0, 153, 255));

        jLabel_eMaticna_knjiga_.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel_eMaticna_knjiga_.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_eMaticna_knjiga_.setText("eMatična knjiga");

        jButton_Odjavi_se_.setBackground(new java.awt.Color(255, 0, 0));
        jButton_Odjavi_se_.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton_Odjavi_se_.setText("Odjavi se");
        jButton_Odjavi_se_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Odjavi_se_ActionPerformed(evt);
            }
        });

        jLabel_administracija.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel_administracija.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_administracija.setText("ADMINISTRACIJA");

        ime_prijavljenog_administratora.setFont(new java.awt.Font("Segoe UI Emoji", 3, 12)); // NOI18N
        ime_prijavljenog_administratora.setForeground(new java.awt.Color(255, 255, 255));
        ime_prijavljenog_administratora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ime_prijavljenog_administratora.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_administrator.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel_administrator.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_administrator.setText("Administrator:");

        javax.swing.GroupLayout jPanel_zaglavljeLayout = new javax.swing.GroupLayout(jPanel_zaglavlje);
        jPanel_zaglavlje.setLayout(jPanel_zaglavljeLayout);
        jPanel_zaglavljeLayout.setHorizontalGroup(
            jPanel_zaglavljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_zaglavljeLayout.createSequentialGroup()
                .addGroup(jPanel_zaglavljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_zaglavljeLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel_administracija)
                        .addGap(449, 449, 449)
                        .addComponent(jLabel_administrator))
                    .addGroup(jPanel_zaglavljeLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel_eMaticna_knjiga_)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_zaglavljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ime_prijavljenog_administratora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Odjavi_se_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_zaglavljeLayout.setVerticalGroup(
            jPanel_zaglavljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_zaglavljeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel_zaglavljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_eMaticna_knjiga_)
                    .addComponent(jButton_Odjavi_se_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_zaglavljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_zaglavljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_administracija)
                        .addComponent(jLabel_administrator))
                    .addComponent(ime_prijavljenog_administratora, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_podnozje.setBackground(new java.awt.Color(0, 153, 255));

        jLabel_autor.setFont(new java.awt.Font("Sitka Heading", 1, 12)); // NOI18N
        jLabel_autor.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_autor.setText("Produced by Severin Knežević");

        jButton_Oprogramu_.setBackground(new java.awt.Color(0, 153, 255));
        jButton_Oprogramu_.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Oprogramu_.setText("O programu");
        jButton_Oprogramu_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Oprogramu_MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_podnozjeLayout = new javax.swing.GroupLayout(jPanel_podnozje);
        jPanel_podnozje.setLayout(jPanel_podnozjeLayout);
        jPanel_podnozjeLayout.setHorizontalGroup(
            jPanel_podnozjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_podnozjeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Oprogramu_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_podnozjeLayout.setVerticalGroup(
            jPanel_podnozjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_podnozjeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_podnozjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_autor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Oprogramu_, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jPanel_izbornik.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_izbornik.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jButton_Upravljaj_korisnicima_.setBackground(new java.awt.Color(51, 255, 255));
        jButton_Upravljaj_korisnicima_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Upravljaj_korisnicima_.setText("Upravljaj korisnicima");
        jButton_Upravljaj_korisnicima_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Upravljaj_korisnicima_ActionPerformed(evt);
            }
        });

        jButton_Dodaj_novog_ucenika_.setBackground(new java.awt.Color(51, 255, 255));
        jButton_Dodaj_novog_ucenika_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Dodaj_novog_ucenika_.setText("Dodaj novog učenika");
        jButton_Dodaj_novog_ucenika_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Dodaj_novog_ucenika_ActionPerformed(evt);
            }
        });

        jButton_Upis_u_maticnu_knjigu_.setBackground(new java.awt.Color(51, 255, 255));
        jButton_Upis_u_maticnu_knjigu_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Upis_u_maticnu_knjigu_.setText("Upis u matičnu knjigu");
        jButton_Upis_u_maticnu_knjigu_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Upis_u_maticnu_knjigu_ActionPerformed(evt);
            }
        });

        jButton_Dodaj_novu_skolsku_godinu_.setBackground(new java.awt.Color(51, 255, 255));
        jButton_Dodaj_novu_skolsku_godinu_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Dodaj_novu_skolsku_godinu_.setText("Dodaj novu školsku godinu");
        jButton_Dodaj_novu_skolsku_godinu_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Dodaj_novu_skolsku_godinu_ActionPerformed(evt);
            }
        });

        jButton_Upravljaj_administratorima_.setBackground(new java.awt.Color(51, 255, 255));
        jButton_Upravljaj_administratorima_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Upravljaj_administratorima_.setText("Upravljaj administratorima");
        jButton_Upravljaj_administratorima_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Upravljaj_administratorima_ActionPerformed(evt);
            }
        });

        jButton_Evidencija_ucenika_.setBackground(new java.awt.Color(51, 255, 255));
        jButton_Evidencija_ucenika_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Evidencija_ucenika_.setText("Evidencija učenika");
        jButton_Evidencija_ucenika_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Evidencija_ucenika_ActionPerformed(evt);
            }
        });

        jButton_Dodaj_novi_razred_.setBackground(new java.awt.Color(51, 255, 255));
        jButton_Dodaj_novi_razred_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Dodaj_novi_razred_.setText("Dodaj novi razred");
        jButton_Dodaj_novi_razred_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Dodaj_novi_razred_ActionPerformed(evt);
            }
        });

        jButton_Dodaj_novu_maticnu_knjigu_.setBackground(new java.awt.Color(51, 255, 255));
        jButton_Dodaj_novu_maticnu_knjigu_.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Dodaj_novu_maticnu_knjigu_.setText("Dodaj novu matičnu knjigu");
        jButton_Dodaj_novu_maticnu_knjigu_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Dodaj_novu_maticnu_knjigu_ActionPerformed(evt);
            }
        });

        jButton_Maticni_podaci_.setBackground(new java.awt.Color(51, 255, 255));
        jButton_Maticni_podaci_.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton_Maticni_podaci_.setText("Matični podaci");
        jButton_Maticni_podaci_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Maticni_podaci_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_izbornikLayout = new javax.swing.GroupLayout(jPanel_izbornik);
        jPanel_izbornik.setLayout(jPanel_izbornikLayout);
        jPanel_izbornikLayout.setHorizontalGroup(
            jPanel_izbornikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_izbornikLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_izbornikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Upravljaj_korisnicima_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Upravljaj_administratorima_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Dodaj_novi_razred_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Dodaj_novu_skolsku_godinu_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton_Maticni_podaci_, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel_izbornikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Evidencija_ucenika_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Dodaj_novog_ucenika_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Upis_u_maticnu_knjigu_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Dodaj_novu_maticnu_knjigu_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_izbornikLayout.setVerticalGroup(
            jPanel_izbornikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_izbornikLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_izbornikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Maticni_podaci_, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jButton_Evidencija_ucenika_, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jButton_Upravljaj_korisnicima_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel_izbornikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Dodaj_novog_ucenika_, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Upravljaj_administratorima_, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_izbornikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Dodaj_novu_maticnu_knjigu_, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jButton_Dodaj_novu_skolsku_godinu_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_izbornikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Dodaj_novi_razred_, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Upis_u_maticnu_knjigu_, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_pozadinaLayout = new javax.swing.GroupLayout(jPanel_pozadina);
        jPanel_pozadina.setLayout(jPanel_pozadinaLayout);
        jPanel_pozadinaLayout.setHorizontalGroup(
            jPanel_pozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_zaglavlje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_podnozje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_pozadinaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_izbornik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        jPanel_pozadinaLayout.setVerticalGroup(
            jPanel_pozadinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_pozadinaLayout.createSequentialGroup()
                .addComponent(jPanel_zaglavlje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_izbornik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_podnozje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_pozadina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_pozadina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Odjavi_se_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Odjavi_se_ActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jButton_Odjavi_se_ActionPerformed

    private void jButton_Upravljaj_korisnicima_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Upravljaj_korisnicima_ActionPerformed
        // TODO add your handling code here:
        Dodavanje_korisnika d_k = new Dodavanje_korisnika();
        d_k.setVisible(true);

    }//GEN-LAST:event_jButton_Upravljaj_korisnicima_ActionPerformed

    private void jButton_Dodaj_novog_ucenika_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Dodaj_novog_ucenika_ActionPerformed
        // TODO add your handling code here:
        Dodavanje_ucenika d_u = new Dodavanje_ucenika();
        d_u.setVisible(true);
    }//GEN-LAST:event_jButton_Dodaj_novog_ucenika_ActionPerformed

    private void jButton_Upis_u_maticnu_knjigu_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Upis_u_maticnu_knjigu_ActionPerformed
        // TODO add your handling code here:
        Upis_maticni_podaci u_m_p = new Upis_maticni_podaci();
        u_m_p.setVisible(true);
    }//GEN-LAST:event_jButton_Upis_u_maticnu_knjigu_ActionPerformed

    private void jButton_Dodaj_novu_skolsku_godinu_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Dodaj_novu_skolsku_godinu_ActionPerformed
        // TODO add your handling code here:
        Dodavanje_skolske_godine d_s_g = new Dodavanje_skolske_godine();
        d_s_g.setVisible(true);
    }//GEN-LAST:event_jButton_Dodaj_novu_skolsku_godinu_ActionPerformed

    private void jButton_Upravljaj_administratorima_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Upravljaj_administratorima_ActionPerformed
        // TODO add your handling code here:
        Dodavanje_admina d_a = new Dodavanje_admina();
        d_a.setVisible(true);
    }//GEN-LAST:event_jButton_Upravljaj_administratorima_ActionPerformed

    private void jButton_Evidencija_ucenika_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Evidencija_ucenika_ActionPerformed
        // TODO add your handling code here:
        Popis_ucenik_uredjivanje p_u = new Popis_ucenik_uredjivanje();
        p_u.setVisible(true);
    }//GEN-LAST:event_jButton_Evidencija_ucenika_ActionPerformed

    private void jButton_Dodaj_novi_razred_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Dodaj_novi_razred_ActionPerformed
        // TODO add your handling code here:
        Dodavanje_razred d_r = new Dodavanje_razred();
        d_r.setVisible(true);
    }//GEN-LAST:event_jButton_Dodaj_novi_razred_ActionPerformed

    private void jButton_Dodaj_novu_maticnu_knjigu_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Dodaj_novu_maticnu_knjigu_ActionPerformed
        // TODO add your handling code here:
        Dodavanje_maticne_knjige d_m_k = new Dodavanje_maticne_knjige();
        d_m_k.setVisible(true);
    }//GEN-LAST:event_jButton_Dodaj_novu_maticnu_knjigu_ActionPerformed

    private void jButton_Maticni_podaci_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Maticni_podaci_ActionPerformed
        // TODO add your handling code here:
        Maticni_podaci m_p = new Maticni_podaci();
        m_p.setVisible(true);
    }//GEN-LAST:event_jButton_Maticni_podaci_ActionPerformed

    private void jButton_Oprogramu_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Oprogramu_MouseClicked
        // TODO add your handling code here:
        Oprogramu o = new Oprogramu();
        o.setVisible(true);
    }//GEN-LAST:event_jButton_Oprogramu_MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sucelje_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sucelje_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sucelje_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sucelje_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sucelje_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ime_prijavljenog_administratora;
    private javax.swing.JButton jButton_Dodaj_novi_razred_;
    private javax.swing.JButton jButton_Dodaj_novog_ucenika_;
    private javax.swing.JButton jButton_Dodaj_novu_maticnu_knjigu_;
    private javax.swing.JButton jButton_Dodaj_novu_skolsku_godinu_;
    private javax.swing.JButton jButton_Evidencija_ucenika_;
    private javax.swing.JButton jButton_Maticni_podaci_;
    private javax.swing.JButton jButton_Odjavi_se_;
    private javax.swing.JButton jButton_Oprogramu_;
    private javax.swing.JButton jButton_Upis_u_maticnu_knjigu_;
    private javax.swing.JButton jButton_Upravljaj_administratorima_;
    private javax.swing.JButton jButton_Upravljaj_korisnicima_;
    private javax.swing.JLabel jLabel_administracija;
    private javax.swing.JLabel jLabel_administrator;
    private javax.swing.JLabel jLabel_autor;
    private javax.swing.JLabel jLabel_eMaticna_knjiga_;
    private javax.swing.JPanel jPanel_izbornik;
    private javax.swing.JPanel jPanel_podnozje;
    private javax.swing.JPanel jPanel_pozadina;
    private javax.swing.JPanel jPanel_zaglavlje;
    // End of variables declaration//GEN-END:variables
}
