/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skola;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Severin
 */
public class Ucenik_uredjivanje extends javax.swing.JFrame {

    /**
     * Creates new form registation
     */
    
    Connection con;
    PreparedStatement pst;
    PreparedStatement pst1;
    ResultSet rs;

    public Ucenik_uredjivanje() {
        initComponents();
        tablica_ucenika();
    }
    
     public void tablica_ucenika()
    {
       
        int c;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ematicna_baza","root",""); 
            pst = con.prepareStatement("select * from ucenik");
            ResultSet Rs = pst.executeQuery();
            
            ResultSetMetaData rd = Rs.getMetaData();
            c = rd.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)jTable_tablica.getModel();
            df.setRowCount(0);
            
            while(Rs.next())
            {
               Vector v2 = new Vector();
               
               for(int i=1; i<c; i++)
               {
                   v2.add(Rs.getString("id"));
                   v2.add(Rs.getString("iducenik"));
                   v2.add(Rs.getString("maticna_knjiga"));
                   v2.add(Rs.getString("maticni_broj"));
                   v2.add(Rs.getString("ime"));
                   v2.add(Rs.getString("prezime"));
                   v2.add(Rs.getString("jmbg"));
                   v2.add(Rs.getString("spol"));
                   v2.add(Rs.getString("roditelj"));
                   v2.add(Rs.getString("datum_rodjenja"));    
                   v2.add(Rs.getString("mjesto_rodjenja"));
                   v2.add(Rs.getString("opcina_rodjenja"));
                   v2.add(Rs.getString("drzava_rodjenja"));
                   v2.add(Rs.getString("drzavljanstvo"));
                   v2.add(Rs.getString("nacionalnost"));
                   v2.add(Rs.getString("godina_prvog_razreda"));
               }
               df.addRow(v2);
            }
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ucenik_uredjivanje.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
           Logger.getLogger(Ucenik_uredjivanje.class.getName()).log(Level.SEVERE, null, ex);
       }
            
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jInternalFrame_formular = new javax.swing.JInternalFrame();
        jLabel_ime = new javax.swing.JLabel();
        jLabel_prezime = new javax.swing.JLabel();
        jLabel_spol = new javax.swing.JLabel();
        jLabel_imena_roditelja = new javax.swing.JLabel();
        jLabel_datum_rodjenja = new javax.swing.JLabel();
        jLabel_mjesto_rodjenja = new javax.swing.JLabel();
        jLabel_opcina_rodjenja = new javax.swing.JLabel();
        jLabel_drzava_rodjenja = new javax.swing.JLabel();
        jLabel_drzavljanin = new javax.swing.JLabel();
        jLabel_narodnost = new javax.swing.JLabel();
        jButton_Spremi_ = new javax.swing.JButton();
        jButton_Odustani_ = new javax.swing.JButton();
        jLabel_maticna_knjiga = new javax.swing.JLabel();
        jLabel_maticni_broj = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtRoditelj = new javax.swing.JTextField();
        txtDatum_rodjenja = new javax.swing.JTextField();
        txtMjesto_rodjenja = new javax.swing.JTextField();
        txtOpcina_rodjenja = new javax.swing.JTextField();
        txtDrzavljanin = new javax.swing.JTextField();
        txtMaticna_knjiga = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtid_Ucenik = new javax.swing.JTextField();
        jLabel_iducenik = new javax.swing.JLabel();
        txtJmbg = new javax.swing.JTextField();
        jLabel_jmbg = new javax.swing.JLabel();
        txtGodina_prvog_razreda = new javax.swing.JTextField();
        jLabel_godina_prvog_razreda = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtMaticni_broj = new javax.swing.JTextField();
        txtSpol = new javax.swing.JTextField();
        txtDrzava_rodjenja = new javax.swing.JTextField();
        txtNarodnost = new javax.swing.JTextField();
        txtrd = new javax.swing.JTextField();
        jLabel_id = new javax.swing.JLabel();
        jScrollPane_tablica = new javax.swing.JScrollPane();
        jTable_tablica = new javax.swing.JTable();
        txtPretrazivac = new javax.swing.JTextField();
        jLabel_pretrazi_tablicu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame_formular.setBackground(new java.awt.Color(204, 204, 204));
        jInternalFrame_formular.setIconifiable(true);
        jInternalFrame_formular.setTitle("Matični podaci učenika");
        jInternalFrame_formular.setToolTipText(" ");
        jInternalFrame_formular.setVisible(true);

        jLabel_ime.setText("Ime");

        jLabel_prezime.setText("Prezime");

        jLabel_spol.setText("Spol");

        jLabel_imena_roditelja.setText("Imena roditelja");

        jLabel_datum_rodjenja.setText("Datum rođenja");

        jLabel_mjesto_rodjenja.setText("Mjesto rođenja");

        jLabel_opcina_rodjenja.setText("Općina rođenja");

        jLabel_drzava_rodjenja.setText("Država rođenja");

        jLabel_drzavljanin.setText("Državljanin");

        jLabel_narodnost.setText("Narodnost");

        jButton_Spremi_.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Spremi_.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton_Spremi_.setText("Spremi");
        jButton_Spremi_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Spremi_ActionPerformed(evt);
            }
        });

        jButton_Odustani_.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Odustani_.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jButton_Odustani_.setText("Odustani");
        jButton_Odustani_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Odustani_ActionPerformed(evt);
            }
        });

        jLabel_maticna_knjiga.setText("Matična knjiga");

        jLabel_maticni_broj.setText("Matični broj ");

        txtRoditelj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoditeljActionPerformed(evt);
            }
        });

        txtDatum_rodjenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatum_rodjenjaActionPerformed(evt);
            }
        });

        txtMaticna_knjiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaticna_knjigaActionPerformed(evt);
            }
        });
        txtMaticna_knjiga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaticna_knjigaKeyReleased(evt);
            }
        });

        txtid_Ucenik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid_UcenikActionPerformed(evt);
            }
        });

        jLabel_iducenik.setText("ID Učenika");

        jLabel_jmbg.setText("JMBG");

        jLabel_godina_prvog_razreda.setText("Godina prvog razreda");

        txtMaticni_broj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaticni_brojActionPerformed(evt);
            }
        });
        txtMaticni_broj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaticni_brojKeyReleased(evt);
            }
        });

        txtrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrdActionPerformed(evt);
            }
        });
        txtrd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrdKeyReleased(evt);
            }
        });

        jLabel_id.setText("ID:");

        javax.swing.GroupLayout jInternalFrame_formularLayout = new javax.swing.GroupLayout(jInternalFrame_formular.getContentPane());
        jInternalFrame_formular.getContentPane().setLayout(jInternalFrame_formularLayout);
        jInternalFrame_formularLayout.setHorizontalGroup(
            jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_formularLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_formularLayout.createSequentialGroup()
                        .addComponent(jButton_Spremi_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Odustani_)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_formularLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jSeparator1)
            .addGroup(jInternalFrame_formularLayout.createSequentialGroup()
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame_formularLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_ime)
                            .addComponent(jLabel_spol)
                            .addComponent(jLabel_prezime)
                            .addComponent(jLabel_imena_roditelja)
                            .addComponent(jLabel_datum_rodjenja)
                            .addComponent(jLabel_mjesto_rodjenja)
                            .addComponent(jLabel_opcina_rodjenja)
                            .addComponent(jLabel_drzava_rodjenja)
                            .addComponent(jLabel_drzavljanin)
                            .addComponent(jLabel_narodnost)
                            .addComponent(jLabel_jmbg))
                        .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_formularLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(txtNarodnost))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_formularLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtDrzava_rodjenja, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtSpol, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPrezime, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDatum_rodjenja, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtRoditelj, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMjesto_rodjenja, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtOpcina_rodjenja)
                                    .addComponent(txtDrzavljanin, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtJmbg, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(jInternalFrame_formularLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_formularLayout.createSequentialGroup()
                                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_maticna_knjiga, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_maticni_broj, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_iducenik, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtid_Ucenik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(txtMaticna_knjiga)
                                    .addComponent(txtMaticni_broj)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_formularLayout.createSequentialGroup()
                                .addComponent(jLabel_godina_prvog_razreda)
                                .addGap(38, 38, 38)
                                .addComponent(txtGodina_prvog_razreda, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_formularLayout.createSequentialGroup()
                                .addComponent(jLabel_id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtrd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jInternalFrame_formularLayout.setVerticalGroup(
            jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame_formularLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_maticna_knjiga)
                    .addComponent(txtMaticna_knjiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_maticni_broj)
                    .addComponent(txtMaticni_broj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid_Ucenik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_iducenik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ime)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_prezime)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_jmbg))
                .addGap(2, 2, 2)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_spol)
                    .addComponent(txtSpol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_imena_roditelja)
                    .addComponent(txtRoditelj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_datum_rodjenja)
                    .addComponent(txtDatum_rodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_mjesto_rodjenja)
                    .addComponent(txtMjesto_rodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame_formularLayout.createSequentialGroup()
                        .addComponent(jLabel_opcina_rodjenja)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame_formularLayout.createSequentialGroup()
                        .addComponent(txtOpcina_rodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGap(0, 0, 0)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_drzava_rodjenja)
                    .addComponent(txtDrzava_rodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_drzavljanin)
                    .addComponent(txtDrzavljanin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_narodnost)
                    .addComponent(txtNarodnost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGodina_prvog_razreda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_godina_prvog_razreda))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame_formularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Spremi_)
                    .addComponent(jButton_Odustani_))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_tablica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ID Učenika", "Matični knjiga", "Matični broj", "Ime", "Prezime", "JMBG", "Spol", "Roditelji", "Datum rođenja", "Grad rođenja", "Općina rođenja", "Država rođenja", "Državljanstvo", "Narodnost", "Godina prvog razreda"
            }
        ));
        jTable_tablica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_tablicaMouseClicked(evt);
            }
        });
        jScrollPane_tablica.setViewportView(jTable_tablica);

        txtPretrazivac.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        txtPretrazivac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPretrazivacKeyReleased(evt);
            }
        });

        jLabel_pretrazi_tablicu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_pretrazi_tablicu.setText("Pretraži  tablicu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame_formular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jLabel_pretrazi_tablicu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPretrazivac, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(268, 268, 268))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane_tablica))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame_formular)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_pretrazi_tablicu)
                    .addComponent(txtPretrazivac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_tablica))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Odustani_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Odustani_ActionPerformed
        // TODO add your handling code here:
        this.hide();
        
    }//GEN-LAST:event_jButton_Odustani_ActionPerformed

    private void jButton_Spremi_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Spremi_ActionPerformed
            DefaultTableModel df = (DefaultTableModel)jTable_tablica.getModel();
            int selectedIndex = jTable_tablica.getSelectedRow();
            int id = Integer.parseInt(df.getValueAt(selectedIndex, 0).toString());
        
           
            String maticna_knjiga = txtMaticna_knjiga.getText();
            String maticni_broj = txtMaticni_broj.getText();
            String iducenik = txtid_Ucenik.getText();
            String ime = txtIme.getText();
            String prezime = txtPrezime.getText();
            String jmbg = txtJmbg.getText();
            String spol = txtSpol.getText();
            String roditelj = txtRoditelj.getText();
            String datum_rodjenja = txtDatum_rodjenja.getText();
            String mjesto_rodjenja = txtMjesto_rodjenja.getText();
            String opcina_rodjenja = txtOpcina_rodjenja.getText();
            String drzava_rodjenja = txtDrzava_rodjenja.getText();
            String drzavljanstvo = txtDrzavljanin.getText();
            String nacionalnost = txtNarodnost.getText();
            String godina_prvog_razreda = txtGodina_prvog_razreda.getText();
            
        try {
       

            // TODO add your handling code here:

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ematicna_baza","root","");

            pst = con.prepareStatement("update ucenik set iducenik=?,maticna_knjiga=?,maticni_broj=?,ime=?,prezime=?,jmbg=?,spol=?,roditelj=?,datum_rodjenja=?,mjesto_rodjenja=?,opcina_rodjenja=?,drzava_rodjenja=?,drzavljanstvo=?,nacionalnost=?,godina_prvog_razreda=? where id=?");

            pst.setString(1, iducenik);
            pst.setString(2, maticna_knjiga);
            pst.setString(3, maticni_broj);
            pst.setString(4, ime);
            pst.setString(5, prezime);
            pst.setString(6, jmbg);
            pst.setString(7, spol);
            pst.setString(8, roditelj);
            pst.setString(9, datum_rodjenja);
            pst.setString(10, mjesto_rodjenja);
            pst.setString(11, opcina_rodjenja);
            pst.setString(12, drzava_rodjenja);
            pst.setString(13, drzavljanstvo);
            pst.setString(14, nacionalnost);
            pst.setString(15, godina_prvog_razreda);
            pst.setInt(16, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Promjene su spremljene");
            

            
            this.hide();
            Ucenik_uredjivanje r = new Ucenik_uredjivanje();
            r.setVisible(true);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ucenik_uredjivanje.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Ucenik_uredjivanje.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_Spremi_ActionPerformed

    private void txtDatum_rodjenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatum_rodjenjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatum_rodjenjaActionPerformed

    private void txtRoditeljActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoditeljActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoditeljActionPerformed

    private void txtid_UcenikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid_UcenikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid_UcenikActionPerformed

    private void txtMaticna_knjigaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaticna_knjigaKeyReleased
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ematicna_baza", "root", "");
            txtid_Ucenik.setText(txtMaticna_knjiga.getText()+txtMaticni_broj.getText() );
            

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ucenik_uredjivanje.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Ucenik_uredjivanje.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtMaticna_knjigaKeyReleased

    private void txtMaticna_knjigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaticna_knjigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaticna_knjigaActionPerformed

    private void txtMaticni_brojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaticni_brojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaticni_brojActionPerformed

    private void txtMaticni_brojKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaticni_brojKeyReleased
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ematicna_baza", "root", "");
            txtid_Ucenik.setText(txtMaticna_knjiga.getText()+txtMaticni_broj.getText() );
            

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ucenik_uredjivanje.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Ucenik_uredjivanje.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtMaticni_brojKeyReleased

    private void jTable_tablicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_tablicaMouseClicked
        DefaultTableModel df = (DefaultTableModel)jTable_tablica.getModel();
        int selectedIndex = jTable_tablica.getSelectedRow();
        
        txtrd.setText(df.getValueAt(selectedIndex, 0).toString());
        txtid_Ucenik.setText(df.getValueAt(selectedIndex, 1).toString());
        txtMaticna_knjiga.setText(df.getValueAt(selectedIndex, 2).toString());
        txtMaticni_broj.setText(df.getValueAt(selectedIndex, 3).toString());
        txtIme.setText(df.getValueAt(selectedIndex, 4).toString());
        txtPrezime.setText(df.getValueAt(selectedIndex, 5).toString());
        txtJmbg.setText(df.getValueAt(selectedIndex, 6).toString());
        txtSpol.setText(df.getValueAt(selectedIndex, 7).toString());
        txtRoditelj.setText(df.getValueAt(selectedIndex, 8).toString());
        txtDatum_rodjenja.setText(df.getValueAt(selectedIndex, 9).toString());
        txtMjesto_rodjenja.setText(df.getValueAt(selectedIndex, 10).toString());
        txtOpcina_rodjenja.setText(df.getValueAt(selectedIndex, 11).toString());
        txtDrzava_rodjenja.setText(df.getValueAt(selectedIndex, 12).toString());
        txtDrzavljanin.setText(df.getValueAt(selectedIndex, 13).toString());
        txtNarodnost.setText(df.getValueAt(selectedIndex, 14).toString());
        txtGodina_prvog_razreda.setText(df.getValueAt(selectedIndex, 15).toString());
        


    }//GEN-LAST:event_jTable_tablicaMouseClicked

    private void txtrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrdActionPerformed

    private void txtrdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrdKeyReleased
        // TODO add your handling code here:
        try {
            pst = con.prepareStatement("select id,iducenik,maticna_knjiga,maticni_broj,ime,prezime,jmbg,spol,roditelj,datum_rodjenja,mjesto_rodjenja,opcina_rodjenja,drzava_rodjenja,drzavljanstvo,nacionalnost,godina_prvog_razreda from ucenik where id=?");
            int id = Integer.parseInt(txtrd.getText());
            pst.setInt(1, id);
            ResultSet rs1 = pst.executeQuery();
            if (rs1.next() == false) {
                txtid_Ucenik.setText("");
                txtMaticna_knjiga.setText("");
                txtMaticni_broj.setText("");
                txtIme.setText("");
                txtPrezime.setText("");
                txtJmbg.setText("");
                txtSpol.setText("");
                txtRoditelj.setText("");
                txtDatum_rodjenja.setText("");
                txtMjesto_rodjenja.setText("");
                txtOpcina_rodjenja.setText("");
                txtDrzava_rodjenja.setText("");
                txtDrzavljanin.setText("");
                txtNarodnost.setText("");
                txtGodina_prvog_razreda.setText("");
                txtid_Ucenik.requestFocus();
            } else {
                txtid_Ucenik.setText(rs1.getString("iducenik"));
                txtMaticna_knjiga.setText(rs1.getString("maticna_knjiga"));
                txtMaticni_broj.setText(rs1.getString("maticni_broj"));
                txtIme.setText(rs1.getString("ime"));
                txtPrezime.setText(rs1.getString("prezime"));
                txtJmbg.setText(rs1.getString("jmbg"));
                txtSpol.setText(rs1.getString("spol"));
                txtRoditelj.setText(rs1.getString("roditelj"));
                txtDatum_rodjenja.setText(rs1.getString("datum_rodjenja"));
                txtMjesto_rodjenja.setText(rs1.getString("mjesto_rodjenja"));
                txtOpcina_rodjenja.setText(rs1.getString("opcina_rodjenja"));
                txtDrzava_rodjenja.setText(rs1.getString("drzava_rodjenja"));
                txtDrzavljanin.setText(rs1.getString("drzavljanstvo"));
                txtNarodnost.setText(rs1.getString("nacionalnost"));
                txtGodina_prvog_razreda.setText(rs1.getString("godina_prvog_razreda"));

            }

        } catch (SQLException ex) {
            Logger.getLogger(Ucenik_uredjivanje.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtrdKeyReleased

    private void txtPretrazivacKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPretrazivacKeyReleased
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ematicna_baza","root","");
            pst = con.prepareStatement("SELECT id,iducenik,maticna_knjiga,maticni_broj,ime,prezime,jmbg,spol,roditelj,datum_rodjenja,mjesto_rodjenja,opcina_rodjenja,drzava_rodjenja,drzavljanstvo,nacionalnost,godina_prvog_razreda FROM ucenik WHERE  ime LIKE  '%"+txtPretrazivac.getText()+"%' OR prezime LIKE  '%"+txtPretrazivac.getText()+"%' OR jmbg LIKE  '%"+txtPretrazivac.getText()+"%' OR datum_rodjenja LIKE  '%"+txtPretrazivac.getText()+"%' OR godina_prvog_razreda LIKE  '%"+txtPretrazivac.getText()+"%' OR roditelj LIKE  '%"+txtPretrazivac.getText()+"%'");
            ResultSet rs = pst.executeQuery();
/*radi uz rs2xml.jar datoteku ucitanu u biblioteku*/         jTable_tablica.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ucenik_uredjivanje.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Ucenik_uredjivanje.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtPretrazivacKeyReleased

            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ucenik_uredjivanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ucenik_uredjivanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ucenik_uredjivanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ucenik_uredjivanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ucenik_uredjivanje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButton_Odustani_;
    private javax.swing.JButton jButton_Spremi_;
    private javax.swing.JInternalFrame jInternalFrame_formular;
    private javax.swing.JLabel jLabel_datum_rodjenja;
    private javax.swing.JLabel jLabel_drzava_rodjenja;
    private javax.swing.JLabel jLabel_drzavljanin;
    private javax.swing.JLabel jLabel_godina_prvog_razreda;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JLabel jLabel_iducenik;
    private javax.swing.JLabel jLabel_ime;
    private javax.swing.JLabel jLabel_imena_roditelja;
    private javax.swing.JLabel jLabel_jmbg;
    private javax.swing.JLabel jLabel_maticna_knjiga;
    private javax.swing.JLabel jLabel_maticni_broj;
    private javax.swing.JLabel jLabel_mjesto_rodjenja;
    private javax.swing.JLabel jLabel_narodnost;
    private javax.swing.JLabel jLabel_opcina_rodjenja;
    private javax.swing.JLabel jLabel_pretrazi_tablicu;
    private javax.swing.JLabel jLabel_prezime;
    private javax.swing.JLabel jLabel_spol;
    private javax.swing.JScrollPane jScrollPane_tablica;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable_tablica;
    private javax.swing.JTextField txtDatum_rodjenja;
    private javax.swing.JTextField txtDrzava_rodjenja;
    private javax.swing.JTextField txtDrzavljanin;
    private javax.swing.JTextField txtGodina_prvog_razreda;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJmbg;
    private javax.swing.JTextField txtMaticna_knjiga;
    private javax.swing.JTextField txtMaticni_broj;
    private javax.swing.JTextField txtMjesto_rodjenja;
    private javax.swing.JTextField txtNarodnost;
    private javax.swing.JTextField txtOpcina_rodjenja;
    private javax.swing.JTextField txtPretrazivac;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtRoditelj;
    private javax.swing.JTextField txtSpol;
    private javax.swing.JTextField txtid_Ucenik;
    private javax.swing.JTextField txtrd;
    // End of variables declaration//GEN-END:variables
}
